[platformio]
default_envs = waveshare_esp32s3

[env]
platform = espressif32@6.3.2
board = esp32-s3-r8-opi
framework = arduino
monitor_speed = 115200
upload_speed = 460800
extra_scripts = pre:tools/pio_set_version.py
build_flags =
  -DCORE_DEBUG_LEVEL=3

[env:waveshare_esp32s3]
build_flags =
  ${env.build_flags}

[env:native_test]
platform = native
framework =
test_framework = unity
test_filter = test_totp
test_build_src = yes
build_src_filter = -<*> +<totp/> -<totp/AccountStore.cpp> -<totp/TimeService.cpp> -<totp/TotpWebServer.cpp> -<totp/TotpApp.cpp> -<totp/TotpBleServer.cpp>
build_flags =
  -std=c++17
  -Itest/support
  -Isrc
